name: Terraform Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  terraform-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "~1.0"

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Terraform Init
      run: terraform init
      env:
        MITTWALD_API_TOKEN: ${{ secrets.MITTWALD_API_TOKEN }}

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Test
      run: terraform test
      env:
        MITTWALD_API_TOKEN: ${{ secrets.MITTWALD_API_TOKEN }}